title_primary: "秋月春风" # the bigger text
title_secondary: "明月守灯寻长梦，梦长寻灯守月明" # the smaller text
personal_site: "/about/" # 指向新创建的个人主页
keywords:

twitter: #username
rss: atom.xml
weibo: #username/id
instagram: #username
github: YukinoshitaSherry
xiaohongshu: 秋月春风

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
# livere: # [data-uid] on livere.com
# disqus: # [short_name] on disqus.com
# dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark


# Show description behind post titles
truncate_len: 0
enableExcerpt: false


# 更新 Giscus 配置
giscus:
  enable: true
  repo: "YukinoshitaSherry/yukinoshitasherry.github.io"
  repo_id: "R_kgDONEFZ0Q"
  category: "General"
  category_id: "DIC_kwDONEFZ0c4CmKE4"
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "light"
  lang: "zh-CN"
  loading: "lazy"
  crossorigin: "anonymous"


